---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: custom
spec:
  requirements:
  - key: "kubernetes.io/os"
    operator: In
    values: ["linux"] 
  - key: "karpenter.k8s.aws/instance-size"
    operator: In
    values: [ nano, micro, small, medium ]
  - key: "karpenter.k8s.aws/instance-family"
    operator: In
    values: [ "m5" ]
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values: ["m"]
  - key: karpenter.sh/capacity-type
    operator: In
    values: ["spot"]

  kubeletConfiguration: 
    containerRuntime: containerd
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi

  providerRef:
    name: custom
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: custom
spec:
  subnetSelector:
    karpenter.sh/discovery: "true"
  securityGroupSelector:
    karpenter.sh/discovery: sak-sergey
  tags:
    karpenter.sh/discovery: sak-sergey
