apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sergeyhovakimyan/argo-infra.git
    targetRevision: HEAD
    path: argocd/manifests/provisioner
  destination:
    server: https://kubernetes.default.svc
